language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
  - "8"
  - "10"
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - npm prune
script:
  - yarn add jest
  - yarn run test -- --coverage --outputFile test-results.json --json
  - yarn run lint
  - yarn run build
  - yarn run danger
  - rm -f test-results.json
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
