language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
before_script:
  - npm prune
script:
  - yarn run test -- --coverage --outputFile test-results.json --json
  - yarn run lint
  - yarn run build
  - yarn run danger
  - rm -f test-results.json
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
